$concise-tag-type-choice /= tagged-concise-appraisal-tag
; tagged-concise-appraisal-tag = #6.510(bytes .cbor concise-appraisal-tag)
tagged-concise-appraisal-tag = tagged-concise-evidence
;tagged-concise-mid-tag = #6.506(bytes .cbor concise-mid-tag)
concise-appraisal-tag = concise-evidence-map