epoch-seconds-type = int
$epoch-timestamp-type /= ~tdate
$epoch-timestamp-type /= ~time

$tagged-epoch-id /= tdate ; string - converted to ~time for comparisons
$tagged-epoch-id /= time ; int or float
$tagged-epoch-id /= #6.26990( epoch-grace-tdate)
$tagged-epoch-id /= #6.26991( epoch-grace-time)

epoch-grace-tdate = [
    epoch: tdate
    grace-period: epoch-seconds-type
]

epoch-grace-time = [
    epoch: time
    grace-period: epoch-seconds-type
]

;
; draft-ietf-rats-epoch-markers
;
epoch-marker = [
    epoch-id: $tagged-epoch-id
    ? bell-veracity-proof
]

; veracity of the bell
bell-veracity-proof = non-empty<{
  ? remote-attestation-evidence
  ? remote-attestation-result
  ? scitt-receipt
}>

remote-attestation-evidence = (1: bytes)
remote-attestation-result = (2: bytes)
scitt-receipt = (3: bytes)
