tagged-exp-epoch-gt = #6.60010([
    op.gt .within epoch-operators
    grace-period: epoch-seconds-type ])

tagged-exp-epoch-ge = #6.60010([
    op.ge .within epoch-operators
    grace-period: epoch-seconds-type ])

tagged-exp-epoch-lt = #6.60010([
    op.lt .within epoch-operators
    grace-period: epoch-seconds-type ])

tagged-exp-epoch-le = #6.60010([
    op.le .within epoch-operators
    grace-period: epoch-seconds-type ])