member = 6
not-member = 7
set-operator = member / not-member

set-digest-type /= [ * digest ]
set-digest-expression = [ set-operator, set-digest-type ]
tagged-set-digest-expression = #6.60010( set-digest-expression )

set-tstr-type /= [ * tstr ]
set-tstr-expression = [ set-operator, set-tstr-type ]
tagged-set-tstr-expression = #6.60010( set-tstr-expression )