$$measurement-values-map-extension //= (
  &(tee.epoch: -90) => $tee-epoch-type
)

$tee-epoch-type /= $epoch-timestamp-type ; Intel profile - ~time / ~tdate
$tee-epoch-type /= epoch-marker ; draft-ietf-rats-epoch-markers
$tee-epoch-type /= etime ; RFC9581
