tagged-exp-time-gt = #6.60030([ 
    gt .within time-operator,
    time ])

tagged-exp-time-ge = #6.60030([ 
    ge .within time-operator,
    time ])

tagged-exp-time-lt = #6.60030([
    lt .within time-operator,
    time ])

tagged-exp-time-le = #6.60030([
    le .within time-operator,
    time ])